language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
script:
  - ./gradlew clean check stage
  - docker build -t therickys93/barorderserver .
  - docker build -t therickys93/barorderdatabase database/
  - docker images | grep "barorder"