language: java
jdk: oraclejdk8
sudo: required
services:
- docker
script:
- "./gradlew clean check jacocoTestReport stage"
- docker build -t therickys93/barorderserver .
- docker build -t therickys93/barorderdatabase database/
- docker build -t therickys93/barorderproxy proxy/
- docker images
- docker images | grep "barorder"
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push therickys93/barorderserver;
  docker push therickys93/barorderdatabase; docker push therickys93/barorderproxy;
  fi
- sh set_tags.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: Ks9G8nTHyQr1O2H6aaK8Ln1SYELNA8opfMEmGUhtAN4MgyQP5HLyyImB5vMiu6Ij3Ucd+vuvHESRG7Wq+2ZPB/3h/biu+j6OVjVT1C6oPVEoWK2u7lhCzVcODxvGAX8+RwuuumvISq35VAlp/2t/MHs+Vex2ZHgKQiCdZogyGSz+VWz9I9ulLmXgyPft24MSPfrxt7vbMlxHRrYl9E/knPSfoRLFpqTZ2N3+md1S8v58NaP7+gVm66A7dWBz2hw8bzJg4dHEpTA+kBysY7cOMCAzLO+wbA5BFqZc8r4iEWDlD07ygT5YPKQyDc2tvBSJ1J8guxAxSyoJ7I+OmDw+ulmci11AUpmf5qRRk1Bgj5g9FEDk1fQfr/4tdjHRT1uZTQv6C0vRqbocTl9MCZK+eMkUACv0xWL/y/gbwYJ8lV6nMRN7TnoVrhRF28ZyZbrKvleRAxfOxm/8LhHIbaWnsvSMIzZ1CFRrWPMJmp8MfpAiGu6FJqeXEymcjmIjN79coqa53cQAP1SznGd6pwIWcfGDawVeyiWD29D9qKbWOWNxtAqFt+ZGO/Jx0rYNzGZQTkXVPa5FACrviBkZ1l+13EeYpveapSHd6dZVWz4tGzrmSwcHe0esym3zS+dsDGVob3Urz6fOSWV+rwv3IlunzMBPpDR6+8120RIgFftsy90=
  file: build/libs/barorder*.jar
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: therickys93/barorder
