version: '2'

services:
  mysql:
    image: therickys93/barorderdatabase
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backbone

  phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    networks:
      - backbone

  barorder:
    image: therickys93/barorderserver
    environment:
      - BARORDER_HOST=mysql
      - BARORDER_USER=root
      - BARORDER_PASSWORD=password
      - BARORDER_DATABASE=barorder
    networks:
      - backbone

  proxy:
    image: therickys93/barorderproxy
    ports:
      - "80:80"
    networks: 
      - backbone

networks:
  backbone:
    driver: bridge