version: '2'

services:
  mysql:
    build: therickys93/barorderdatabase
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backbone

  barorder:
    build: therickys93/barorderserver
    environment:
      - BARORDER_HOST=mysql
      - BARORDER_USER=root
      - BARORDER_PASSWORD=password
      - BARORDER_DATABASE=barorder
    ports:
      - "80:8080"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge