version: '2'

services:
  mysql:
    build: ./database/
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
  barorder:
    build: .
    environment:
      - BARORDER_HOST=mysql
      - BARORDER_USER=root
      - BARORDER_PASSWORD=password
      - BARORDER_DATABASE=barorder
    ports:
      - "80:8080"