version: '2'

services:
  mysql:
    build: ./database/
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backbone

  phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    networks:
      - backbone

  barorder:
    build: .
    environment:
      - BARORDER_HOST=mysql
      - BARORDER_USER=root
      - BARORDER_PASSWORD=password
      - BARORDER_DATABASE=barorder
    ports:
      - "80:8080"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge