version: '3'

services:
  mysql:
    image: therickys93/barorderdatabase
    environment:
      - MYSQL_ROOT_PASSWORD=password

  barorder:
    image: therickys93/barorderserver
    environment:
      - BARORDER_HOST=mysql
      - BARORDER_USER=root
      - BARORDER_PASSWORD=password
      - BARORDER_DATABASE=barorder
  
  proxy:
    image: therickys93/barorderproxy
    ports:
      - "80:80"
